# Generated by Django 3.2.7 on 2021-11-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Changed Yet', max_length=20)),
                ('state', models.BooleanField(default=False)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
