# Generated by Django 3.2.7 on 2021-11-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pin_type',
            field=models.BooleanField(default=False),
        ),
    ]
